// This file is generated by Velite

import type __vc from '../velite.config.js'

type Collections = typeof __vc.collections

export type Project = Collections['projects']['schema']['_output']
export declare const projects: Project[]

export type Course = Collections['courses']['schema']['_output']
export declare const courses: Course[]
